import Link from 'next/link'
import './globals.css'
import Control from './Control'
export const metadata = {
  title: 'Web tuto',
  description: 'Generated by su',
}

export default async function RootLayout({ children }) {
  const response = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {
    cache: 'no-store',
  })
  const topics = await response.json()
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map(el => {
            return (
              <li key={el.id}>
                <Link href={`/read/${el.id}`}>{el.title}</Link>
              </li>
            )
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
